import { NextResponse } from "next/server"
import type { NextRequest } from "next/server"

export function proxy(request: NextRequest) {
    const token = request.cookies.get("access_token")?.value
    const role = request.cookies.get("user_role")?.value

    const { pathname } = request.nextUrl

    const publicRoutes = ["/login", "/register"]

    if (publicRoutes.includes(pathname)) {
        return NextResponse.next()
    }

    if (!token) {
        return NextResponse.redirect(new URL("/login", request.url))
    }

    // Normalize role string (removes whitespace/encodes)
    const normalizedRole = role?.toLowerCase().trim() || ""

    // If role is invalid or missing, redirect them to login to prevent loops
    if (normalizedRole !== "student" && normalizedRole !== "teacher") {
        return NextResponse.redirect(new URL("/login", request.url))
    }

    // Student trying to access teacher routes
    if (pathname.startsWith("/teacher") && normalizedRole !== "teacher") {
        return NextResponse.redirect(new URL("/student", request.url))
    }

    // Teacher trying to access student routes
    if (pathname.startsWith("/student") && normalizedRole !== "student") {
        return NextResponse.redirect(new URL("/teacher", request.url))
    }

    return NextResponse.next()
}

export const config = {
    matcher: ["/student/:path*", "/teacher/:path*"],
}
//in my project i dont want teh direct involvment of like student giving queizes on the platform submiting assignments i just want that the student can see the courses created by the teachers of differernt universities and can access the material uploaded by them if permited by teh teacher and then can generate the notes or prepare from it and teacher can generate their quizes for their uni assesments or assignmetns and download as word or pdf file and we will keep the files generated by the teachers and students so if the need it again then can acess the previous ones instead of generating the new again 