"use client"

import { useState } from "react"
import { Sparkles, Bot, FileText, CheckCircle2, ChevronRight, GraduationCap, UploadCloud } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"

export default function StudentAIGeneratorPage() {
  const [generationType, setGenerationType] = useState("Flashcards")
  const [sourceType, setSourceType] = useState("course") // 'course' | 'personal'
  const [selectedCourse, setSelectedCourse] = useState("")
  const [selectedMaterial, setSelectedMaterial] = useState("")
  const [prompt, setPrompt] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [isCompleted, setIsCompleted] = useState(false)

  const handleGenerate = () => {
    setIsGenerating(true)
    // Simulate AI generation delay
    setTimeout(() => {
      setIsGenerating(false)
      setIsCompleted(true)
    }, 2000)
  }

  if (isCompleted) {
    return (
      <div className="max-w-2xl mx-auto mt-12">
        <Card className="text-center p-8 border-2 border-primary/20 shadow-lg">
          <div className="flex justify-center mb-6">
            <div className="p-4 rounded-full bg-primary/10 text-primary">
              <Sparkles className="size-12" />
            </div>
          </div>
          <CardTitle className="text-3xl font-bold mb-2">Generation Complete!</CardTitle>
          <CardDescription className="text-lg mb-8">
            Your {generationType} have been successfully generated by the AI assistant.
          </CardDescription>
          
          <div className="bg-muted/30 rounded-xl p-6 mb-8 text-left">
             <p className="text-sm font-medium text-muted-foreground uppercase tracking-wide mb-3 flex items-center gap-2">
               <Bot className="size-4" /> Generation Summary
             </p>
             <ul className="space-y-2 text-sm">
                <li className="flex justify-between border-b pb-2">
                  <span className="text-muted-foreground">Type:</span>
                  <span className="font-medium">{generationType}</span>
                </li>
                <li className="flex justify-between border-b pb-2">
                  <span className="text-muted-foreground">Source:</span>
                  <span className="font-medium truncate max-w-[200px]">
                    {sourceType === "course" ? "Course Material" : "Personal Upload"}
                  </span>
                </li>
             </ul>
          </div>

          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Button onClick={() => window.location.href = "/student/notes"} variant="default">
              View Generated Notes
            </Button>
            <Button onClick={() => setIsCompleted(false)} variant="outline">
              Generate Something Else
            </Button>
          </div>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      {/* Page Header */}
      <div>
        <h1 className="text-3xl font-bold tracking-tight flex items-center gap-3">
          <div className="p-2 bg-primary/10 rounded-lg text-primary">
            <Sparkles className="size-6" />
          </div>
          Global AI Generator
        </h1>
        <p className="mt-2 text-muted-foreground text-lg">
          Centralized AI hub to create your own practice exams, flashcards, or study guides from any of your courses or personal files.
        </p>
      </div>

      <Card className="border-2 shadow-sm">
        <CardHeader className="bg-muted/20 border-b pb-6">
          <CardTitle>Configure Your Generation</CardTitle>
          <CardDescription>Follow the steps below to instruct the AI what to build for you.</CardDescription>
        </CardHeader>

        <CardContent className="space-y-8 pt-8">
          
          {/* STEP 1 */}
          <div className="space-y-4">
            <h3 className="text-base font-semibold flex items-center gap-2">
              <span className="flex size-6 items-center justify-center rounded-full bg-primary text-primary-foreground text-xs">1</span>
              What would you like to build?
            </h3>
            <div className="pl-8 grid grid-cols-2 md:grid-cols-4 gap-4">
              {["Flashcards", "Summary", "Practice Quiz", "Study Guide"].map((type) => (
                <div 
                  key={type}
                  onClick={() => setGenerationType(type)}
                  className={`border-2 rounded-xl p-4 cursor-pointer text-center transition-all ${
                    generationType === type 
                      ? "border-primary bg-primary/5 text-primary shadow-sm" 
                      : "border-muted hover:border-primary/40 text-muted-foreground hover:text-foreground hover:bg-muted/20"
                  }`}
                >
                  <Bot className={`size-6 mx-auto mb-2 ${generationType === type ? "text-primary" : "text-muted-foreground"}`} />
                  <span className="font-medium text-sm">{type}</span>
                </div>
              ))}
            </div>
          </div>

          {/* STEP 2 */}
          <div className="space-y-4">
            <h3 className="text-base font-semibold flex items-center gap-2">
              <span className="flex size-6 items-center justify-center rounded-full bg-primary text-primary-foreground text-xs">2</span>
              Where should the AI pull the information from?
            </h3>
            <div className="pl-8 space-y-6">
              <RadioGroup value={sourceType} onValueChange={setSourceType} className="flex gap-6">
                <div className="flex items-center space-x-2">
                  <RadioGroupItem value="course" id="source-course" />
                  <Label htmlFor="source-course" className="flex items-center gap-2 cursor-pointer">
                    <GraduationCap className="size-4" /> Enrolled Courses
                  </Label>
                </div>
                <div className="flex items-center space-x-2">
                  <RadioGroupItem value="personal" id="source-personal" />
                  <Label htmlFor="source-personal" className="flex items-center gap-2 cursor-pointer">
                    <UploadCloud className="size-4" /> Personal Uploads
                  </Label>
                </div>
              </RadioGroup>

              <div className="grid sm:grid-cols-2 gap-4 bg-muted/20 p-4 rounded-xl border">
                {sourceType === "course" ? (
                  <>
                    <div className="space-y-2">
                      <Label>Select Course</Label>
                      <Select value={selectedCourse} onValueChange={setSelectedCourse}>
                        <SelectTrigger className="bg-background">
                          <SelectValue placeholder="Choose a course..." />
                        </SelectTrigger>
                        <SelectContent className="bg-background">
                          <SelectItem value="cs101">Introduction to Computer Science</SelectItem>
                          <SelectItem value="eng202">Advanced Literature</SelectItem>
                          <SelectItem value="phys101">Quantum Physics</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="space-y-2">
                      <Label>Select Material (Optional)</Label>
                      <Select value={selectedMaterial} onValueChange={setSelectedMaterial} disabled={!selectedCourse}>
                        <SelectTrigger className="bg-background">
                          <SelectValue placeholder={selectedCourse ? "Select specific lecture..." : "Select course first"} />
                        </SelectTrigger>
                        <SelectContent className="bg-background">
                          <SelectItem value="l1">Lecture 1 - Basics.pdf</SelectItem>
                          <SelectItem value="l2">Chapter 3 Slides.pptx</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </>
                ) : (
                  <div className="space-y-2 col-span-2">
                    <Label>Select Personal File</Label>
                    <Select value={selectedMaterial} onValueChange={setSelectedMaterial}>
                      <SelectTrigger className="bg-background w-full sm:w-1/2">
                        <SelectValue placeholder="Choose from your Vault..." />
                      </SelectTrigger>
                      <SelectContent className="bg-background">
                        <SelectItem value="p1">My_Research_Paper.pdf</SelectItem>
                        <SelectItem value="p2">Chapter_5_Draft.docx</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* STEP 3 */}
          <div className="space-y-4">
            <h3 className="text-base font-semibold flex items-center gap-2">
              <span className="flex size-6 items-center justify-center rounded-full bg-primary text-primary-foreground text-xs">3</span>
              Additional specific instructions (Optional)
            </h3>
            <div className="pl-8">
              <Textarea 
                placeholder="E.g. Make sure the flashcards focus heavily on the mathematical formulas..."
                className="resize-none min-h-24"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
              />
            </div>
          </div>

        </CardContent>

        <CardFooter className="bg-muted/10 border-t p-6 flex justify-end">
          <Button 
            className="w-full sm:w-auto min-w-40" 
            size="lg"
            onClick={handleGenerate}
            disabled={isGenerating || (sourceType === "course" && !selectedCourse) || (sourceType === "personal" && !selectedMaterial)}
          >
            {isGenerating ? (
              "AI is working..."
            ) : (
              <>
                Generate {generationType} <ChevronRight className="ml-2 size-4" />
              </>
            )}
          </Button>
        </CardFooter>
      </Card>
    </div>
  )
}
